# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mun's home
email: quangnd.edu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning to become a writter. I will write about technology, programming
  music, running, books, life...Will you follow me?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://quangnd.github.io" # the base hostname & protocol for your site
twitter_username: quangndedu
github_username:  quangnd

# Build settings
markdown: kramdown
